export type Language = 'en' | 'ru';

export interface Translation {
  [key: string]: string;
}

export interface Translations {
  [key: string]: Translation;
}

export const translations: Translations = {
  en: {
    // Common
    language: 'Language',
    english: 'English',
    russian: 'Russian',
    theme: 'Theme',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    
    // Navigation
    home: 'Home',
    catalog: 'Catalog',
    cart: 'Cart',
    account: 'Account',
    
    // Home
    furnitureStore: 'Furniture Store',
    discoverFurniture: 'Discover beautiful furniture for your home',
    specialOffers: 'Special Offers',
    popularItems: 'Popular Items',
    topRated: 'Top Rated',
    
    // Catalog
    filter: 'Filter',
    sort: 'Sort',
    priceRange: 'Price Range',
    productType: 'Product Type',
    minimumRating: 'Minimum Rating',
    reset: 'Reset',
    applyFilters: 'Apply Filters',
    sortBy: 'Sort By',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    popularity: 'Popularity',
    rating: 'Rating',
    apply: 'Apply',
    noProductsFound: 'No products found',
    adjustFilters: 'Try adjusting your filters or search query',
    clearFilters: 'Clear Filters',
    searchProducts: 'Search products...',
    
    // Product
    addToCart: 'Add to Cart',
    description: 'Description',
    details: 'Details',
    category: 'Category',
    availability: 'Availability',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    addedToCart: 'added to cart',
    purchases: 'purchases',
    
    // Cart
    yourCartIsEmpty: 'Your cart is empty',
    addProductsToCart: 'Add some products to your cart to see them here',
    continueShopping: 'Continue Shopping',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    total: 'Total',
    checkout: 'Checkout',
    loginToCheckout: 'Login to Checkout',
    orderPlacedSuccess: 'Order placed successfully!',
    paymentFailed: 'Failed to process payment. Please try again.',
    pleaseLogin: 'Please log in to complete your purchase',
    proceedToCheckout: 'Proceed to Checkout',
    calculatedAtCheckout: 'Calculated at checkout',
    
    // Checkout
    contactInfo: 'Contact Information',
    deliveryMethod: 'Delivery Method',
    deliveryAddress: 'Delivery Address',
    paymentMethod: 'Payment Method',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    phone: 'Phone',
    yourPhone: 'Your phone number',
    address: 'Address',
    yourAddress: 'Your street address',
    city: 'City',
    yourCity: 'Your city',
    postalCode: 'Postal Code',
    yourPostalCode: 'Your postal code',
    courierDelivery: 'Courier Delivery',
    deliveryTime: 'Delivery in 1-3 days',
    pickupFromStore: 'Pickup from Store',
    pickupTime: 'Available in 24 hours',
    cardPayment: 'Credit/Debit Card',
    cashOnDelivery: 'Cash on Delivery',
    fillAllFields: 'Please fill in all required fields',
    
    // Account
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    signInAccess: 'Sign in to access your account',
    fillDetails: 'Fill in your details to get started',
    name: 'Name',
    yourName: 'Your name',
    email: 'Email',
    emailPlaceholder: 'your.email@example.com',
    password: 'Password',
    yourPassword: 'Your password',
    confirmPassword: 'Confirm Password',
    confirmYourPassword: 'Confirm your password',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    demoCredentials: 'Demo credentials: user@example.com / password',
    accountInformation: 'Account Information',
    orderHistory: 'Order History',
    items: 'items',
    logOut: 'Log Out',
    loggedOut: 'You have been logged out',
    invalidCredentials: 'Invalid email or password',
    emailInUse: 'Email already in use',
    passwordsNotMatch: 'Passwords do not match',
    pleaseEnterEmail: 'Please enter your email',
    pleaseEnterPassword: 'Please enter your password',
    pleaseEnterName: 'Please enter your name',
    order: 'Order',
    noOrdersFound: 'No orders found',
    
    // Order Status
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    
    // Order Actions
    showItems: 'Show Items',
    hideItems: 'Hide Items',
    trackOrder: 'Track Order',
    hideTracking: 'Hide Tracking',
    cancelOrder: 'Cancel Order',
    orderItems: 'Order Items',
    quantity: 'Quantity',
    orderNumber: 'Order #',
    
    // Order Cancellation
    cancelOrderTitle: 'Cancel Order',
    cancelOrderConfirm: 'Are you sure you want to cancel this order?',
    yes: 'Yes',
    no: 'No',
    orderCancelled: 'Order has been cancelled',
    
    // Tracking
    trackingInformation: 'Tracking Information',
    trackingNumber: 'Tracking Number',
    estimatedDelivery: 'Estimated Delivery',
    currentLocation: 'Current Location',
    sortingCenter: 'Sorting Center',
    orderPlaced: 'Order Placed',
    orderProcessed: 'Order Processed',
    inTransit: 'In Transit',
    outForDelivery: 'Out for Delivery',
    deliveredStatus: 'Delivered',
    
    // Profile Editing
    edit: 'Edit',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    profileUpdated: 'Profile updated successfully',
    updateFailed: 'Failed to update profile',
    invalidEmail: 'Please enter a valid email address',
    notifications: 'Notifications',
    enabled: 'Enabled',
    disabled: 'Disabled',
    enableNotifications: 'Enable Notifications',
    
    // User Roles
    adminPanel: 'Admin Panel',
    adminPanelAccess: 'Admin Panel Access',
    manageProducts: 'Manage Products',
    manageUsers: 'Manage Users',
    manageOrders: 'Manage Orders',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    editUser: 'Edit User',
    deleteUser: 'Delete User',
    editOrder: 'Edit Order',
    adminDashboard: 'Admin Dashboard',
    statistics: 'Statistics',
    totalProducts: 'Total Products',
    totalUsers: 'Total Users',
    totalOrders: 'Total Orders',
    revenue: 'Revenue',
    adminLogin: 'Admin Login',
    moderatorLogin: 'Moderator Login',
    userLogin: 'User Login',
    adminCredentials: 'Admin: admin@example.com / password',
    moderatorCredentials: 'Moderator: moderator@example.com / password',
    userRole: 'User Role',
    admin: 'Administrator',
    moderator: 'Moderator',
    visitor: 'Customer',
    accessDenied: 'Access Denied',
    noPermission: 'You do not have permission to access this feature',
    backToAccount: 'Back to Account',
    productManagement: 'Product Management',
    userManagement: 'User Management',
    orderManagement: 'Order Management',
  },
  ru: {
    // Common
    language: 'Язык',
    english: 'Английский',
    russian: 'Русский',
    theme: 'Тема',
    lightTheme: 'Светлая',
    darkTheme: 'Темная',
    
    // Navigation
    home: 'Главная',
    catalog: 'Каталог',
    cart: 'Корзина',
    account: 'Аккаунт',
    
    // Home
    furnitureStore: 'Мебельный Магазин',
    discoverFurniture: 'Откройте для себя красивую мебель для вашего дома',
    specialOffers: 'Специальные предложения',
    popularItems: 'Популярные товары',
    topRated: 'Лучшие по рейтингу',
    
    // Catalog
    filter: 'Фильтр',
    sort: 'Сортировка',
    priceRange: 'Диапазон цен',
    productType: 'Тип товара',
    minimumRating: 'Минимальный рейтинг',
    reset: 'Сбросить',
    applyFilters: 'Применить фильтры',
    sortBy: 'Сортировать по',
    priceLowToHigh: 'Цена: от низкой к высокой',
    priceHighToLow: 'Цена: от высокой к низкой',
    popularity: 'Популярность',
    rating: 'Рейтинг',
    apply: 'Применить',
    noProductsFound: 'Товары не найдены',
    adjustFilters: 'Попробуйте изменить фильтры или поисковый запрос',
    clearFilters: 'Очистить фильтры',
    searchProducts: 'Поиск товаров...',
    
    // Product
    addToCart: 'Добавить в корзину',
    description: 'Описание',
    details: 'Детали',
    category: 'Категория',
    availability: 'Наличие',
    inStock: 'В наличии',
    outOfStock: 'Нет в наличии',
    addedToCart: 'добавлен в корзину',
    purchases: 'покупок',
    
    // Cart
    yourCartIsEmpty: 'Ваша корзина пуста',
    addProductsToCart: 'Добавьте товары в корзину, чтобы увидеть их здесь',
    continueShopping: 'Продолжить покупки',
    subtotal: 'Подытог',
    shipping: 'Доставка',
    free: 'Бесплатно',
    total: 'Итого',
    checkout: 'Оформить заказ',
    loginToCheckout: 'Войдите для оформления',
    orderPlacedSuccess: 'Заказ успешно размещен!',
    paymentFailed: 'Не удалось обработать платеж. Пожалуйста, попробуйте снова.',
    pleaseLogin: 'Пожалуйста, войдите, чтобы завершить покупку',
    proceedToCheckout: 'Перейти к оформлению',
    calculatedAtCheckout: 'Рассчитывается при оформлении',
    
    // Checkout
    contactInfo: 'Контактная информация',
    deliveryMethod: 'Способ доставки',
    deliveryAddress: 'Адрес доставки',
    paymentMethod: 'Способ оплаты',
    orderSummary: 'Сводка заказа',
    placeOrder: 'Разместить заказ',
    phone: 'Телефон',
    yourPhone: 'Ваш номер телефона',
    address: 'Адрес',
    yourAddress: 'Ваш адрес',
    city: 'Город',
    yourCity: 'Ваш город',
    postalCode: 'Почтовый индекс',
    yourPostalCode: 'Ваш почтовый индекс',
    courierDelivery: 'Доставка курьером',
    deliveryTime: 'Доставка за 1-3 дня',
    pickupFromStore: 'Самовывоз из магазина',
    pickupTime: 'Доступно через 24 часа',
    cardPayment: 'Оплата картой',
    cashOnDelivery: 'Оплата при получении',
    fillAllFields: 'Пожалуйста, заполните все обязательные поля',
    
    // Account
    welcomeBack: 'С возвращением',
    createAccount: 'Создать аккаунт',
    signInAccess: 'Войдите, чтобы получить доступ к вашему аккаунту',
    fillDetails: 'Заполните данные, чтобы начать',
    name: 'Имя',
    yourName: 'Ваше имя',
    email: 'Email',
    emailPlaceholder: 'ваш.email@example.com',
    password: 'Пароль',
    yourPassword: 'Ваш пароль',
    confirmPassword: 'Подтвердите пароль',
    confirmYourPassword: 'Подтвердите ваш пароль',
    signIn: 'Войти',
    signUp: 'Зарегистрироваться',
    dontHaveAccount: "Нет аккаунта?",
    alreadyHaveAccount: "Уже есть аккаунт?",
    demoCredentials: 'Демо-данные: user@example.com / password',
    accountInformation: 'Информация об аккаунте',
    orderHistory: 'История заказов',
    items: 'товаров',
    logOut: 'Выйти',
    loggedOut: 'Вы вышли из системы',
    invalidCredentials: 'Неверный email или пароль',
    emailInUse: 'Email уже используется',
    passwordsNotMatch: 'Пароли не совпадают',
    pleaseEnterEmail: 'Пожалуйста, введите ваш email',
    pleaseEnterPassword: 'Пожалуйста, введите ваш пароль',
    pleaseEnterName: 'Пожалуйста, введите ваше имя',
    order: 'Заказ',
    noOrdersFound: 'Заказы не найдены',
    
    // Order Status
    processing: 'В обработке',
    shipped: 'Отправлен',
    delivered: 'Доставлен',
    cancelled: 'Отменен',
    
    // Order Actions
    showItems: 'Показать товары',
    hideItems: 'Скрыть товары',
    trackOrder: 'Отследить заказ',
    hideTracking: 'Скрыть отслеживание',
    cancelOrder: 'Отменить заказ',
    orderItems: 'Товары в заказе',
    quantity: 'Количество',
    orderNumber: 'Заказ №',
    
    // Order Cancellation
    cancelOrderTitle: 'Отмена заказа',
    cancelOrderConfirm: 'Вы уверены, что хотите отменить этот заказ?',
    yes: 'Да',
    no: 'Нет',
    orderCancelled: 'Заказ был отменен',
    
    // Tracking
    trackingInformation: 'Информация об отслеживании',
    trackingNumber: 'Номер отслеживания',
    estimatedDelivery: 'Ожидаемая доставка',
    currentLocation: 'Текущее местоположение',
    sortingCenter: 'Сортировочный центр',
    orderPlaced: 'Заказ размещен',
    orderProcessed: 'Заказ обработан',
    inTransit: 'В пути',
    outForDelivery: 'Передан курьеру',
    deliveredStatus: 'Доставлен',
    
    // Profile Editing
    edit: 'Изменить',
    editProfile: 'Редактировать профиль',
    saveChanges: 'Сохранить изменения',
    cancel: 'Отмена',
    profileUpdated: 'Профиль успешно обновлен',
    updateFailed: 'Не удалось обновить профиль',
    invalidEmail: 'Пожалуйста, введите корректный email',
    notifications: 'Уведомления',
    enabled: 'Включены',
    disabled: 'Отключены',
    enableNotifications: 'Включить уведомления',
    
    // User Roles
    adminPanel: 'Панель администратора',
    adminPanelAccess: 'Доступ к панели администратора',
    manageProducts: 'Управление товарами',
    manageUsers: 'Управление пользователями',
    manageOrders: 'Управление заказами',
    addProduct: 'Добавить товар',
    editProduct: 'Редактировать товар',
    deleteProduct: 'Удалить товар',
    editUser: 'Редактировать пользователя',
    deleteUser: 'Удалить пользователя',
    editOrder: 'Редактировать заказ',
    adminDashboard: 'Панель управления',
    statistics: 'Статистика',
    totalProducts: 'Всего товаров',
    totalUsers: 'Всего пользователей',
    totalOrders: 'Всего заказов',
    revenue: 'Выручка',
    adminLogin: 'Вход для администратора',
    moderatorLogin: 'Вход для модератора',
    userLogin: 'Вход для пользователя',
    adminCredentials: 'Админ: admin@example.com / password',
    moderatorCredentials: 'Модератор: moderator@example.com / password',
    userRole: 'Роль пользователя',
    admin: 'Администратор',
    moderator: 'Модератор',
    visitor: 'Покупатель',
    accessDenied: 'Доступ запрещен',
    noPermission: 'У вас нет прав для доступа к этой функции',
    backToAccount: 'Вернуться в аккаунт',
    productManagement: 'Управление товарами',
    userManagement: 'Управление пользователями',
    orderManagement: 'Управление заказами',
  }
};

export default translations;